spring:
  datasource:
    url: jdbc:mysql://localhost/suresh
    username: root
    password: rasaspsi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop